spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://stampy.db.elephantsql.com:5432/vcvhkedf?user=vcvhkedf&password=z_ScfY5glXDMHwW7Q_CRI91BcUdJCY55'
    username: vcvhkedf
    password: z_ScfY5glXDMHwW7Q_CRI91BcUdJCY55
    adapter: POSTGRESQL
    streaming: false