spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'postgres://vcvhkedf:z_ScfY5glXDMHwW7Q_CRI91BcUdJCY55@stampy.db.elephantsql.com:5432/vcvhkedf'
    username: vcvhkedf
    password: z_ScfY5glXDMHwW7Q_CRI91BcUdJCY55
    adapter: POSTGRESQL
    streaming: false